# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facegui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TubesAlgeo(object):
    def setupUi(self, Window):
        Window.setObjectName("TubesAlgeo")
        Window.resize(700, 350)
        Window.setMinimumSize(QtCore.QSize(700, 350))
        Window.setMaximumSize(QtCore.QSize(700, 350))
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 201, 191))
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 50, 71, 71))
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(610, 50, 71, 71))
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 50, 71, 71))
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 50, 71, 71))
        self.label_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(340, 50, 71, 71))
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(610, 160, 71, 71))
        self.label_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 160, 71, 71))
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(340, 160, 71, 71))
        self.label_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(520, 160, 71, 71))
        self.label_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(430, 160, 71, 71))
        self.label_11.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(270, 130, 35, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(360, 130, 35, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(540, 130, 35, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(630, 130, 35, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(450, 130, 35, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(270, 240, 35, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(360, 240, 35, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(450, 240, 35, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(540, 240, 35, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(630, 240, 35, 16))
        self.label_21.setObjectName("label_21")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(90, 250, 61, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(10, 10, 671, 21))
        self.label_33.setObjectName("label_33")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 280, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.hide()
        self.progressBar.setObjectName("progressBar")
        Window.setCentralWidget(self.centralwidget)
        # Menu Bar
        self.menubar = QtWidgets.QMenuBar()

        self.menuActions = self.menubar.addMenu("Actions")
        self.genAct = self.menuActions.addAction("Generate Database")
        self.genAct.triggered.connect(Window.generate)
        self.testAct = self.menuActions.addAction("Test File")
        self.testAct.triggered.connect(Window.test)

        Window.setMenuBar(self.menubar)
        

        """
        self.menubar = Open(TubesAlgeo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        TubesAlgeo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TubesAlgeo)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        TubesAlgeo.setStatusBar(self.statusbar)
        self.actionFile = QtWidgets.QAction(TubesAlgeo)
        self.actionFile.setObjectName("actionFile")
        self.actionOpen = QtWidgets.QAction(TubesAlgeo)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(TubesAlgeo)
        self.actionSave.setObjectName("actionSave")
        self.actionTest_File = QtWidgets.QAction(TubesAlgeo)
        self.actionTest_File.setObjectName("actionTest_File")
        self.menuOpen.addAction(self.actionOpen)
        self.menuOpen.addAction(self.actionTest_File)
        self.menubar.addAction(self.menuOpen.menuAction())"""

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, TubesAlgeo):
        _translate = QtCore.QCoreApplication.translate
        TubesAlgeo.setWindowTitle(_translate("TubesAlgeo", "MainWindow"))
        self.label.setText(_translate("TubesAlgeo", "<html><head/><body><p><img src=\":/Image/dataset/Aaron Paul22_265.jpg\"/></p></body></html>"))
        self.label_2.setText(_translate("TubesAlgeo", "<html><head/><body><p><img src=\":/Image/dataset/Aaron Paul22_265.jpg\"/></p></body></html>"))
        self.label_4.setText(_translate("TubesAlgeo", "<html><head/><body><p><img src=\":/Image/dataset/Aaron Paul22_265.jpg\"/></p></body></html>"))
        self.label_5.setText(_translate("TubesAlgeo", "<html><head/><body><p><img src=\":/Image/dataset/Aaron Paul22_265.jpg\"/></p></body></html>"))
        self.label_6.setText(_translate("TubesAlgeo", "<html><head/><body><p><img src=\":/Image/dataset/Aaron Paul22_265.jpg\"/></p></body></html>"))
        self.label_7.setText(_translate("TubesAlgeo", "<html><head/><body><p><img src=\":/Image/dataset/Aaron Paul22_265.jpg\"/></p></body></html>"))
        self.label_8.setText(_translate("TubesAlgeo", "<html><head/><body><p><img src=\":/Image/dataset/Aaron Paul22_265.jpg\"/></p></body></html>"))
        self.label_3.setText(_translate("TubesAlgeo", "<html><head/><body><p><img src=\":/Image/dataset/Aaron Paul22_265.jpg\"/></p></body></html>"))
        self.label_9.setText(_translate("TubesAlgeo", "<html><head/><body><p><img src=\":/Image/dataset/Aaron Paul22_265.jpg\"/></p></body></html>"))
        self.label_10.setText(_translate("TubesAlgeo", "<html><head/><body><p><img src=\":/Image/dataset/Aaron Paul22_265.jpg\"/></p></body></html>"))
        self.label_11.setText(_translate("TubesAlgeo", "<html><head/><body><p><img src=\":/Image/dataset/Aaron Paul22_265.jpg\"/></p></body></html>"))
        self.label_12.setText(_translate("TubesAlgeo", "<html><head/><body><p align=\"center\">1</p></body></html>"))
        self.label_13.setText(_translate("TubesAlgeo", "<html><head/><body><p align=\"center\">2</p></body></html>"))
        self.label_14.setText(_translate("TubesAlgeo", "<html><head/><body><p align=\"center\">4</p></body></html>"))
        self.label_15.setText(_translate("TubesAlgeo", "<html><head/><body><p align=\"center\">5</p></body></html>"))
        self.label_16.setText(_translate("TubesAlgeo", "<html><head/><body><p align=\"center\">3</p></body></html>"))
        self.label_17.setText(_translate("TubesAlgeo", "<html><head/><body><p align=\"center\">6</p></body></html>"))
        self.label_18.setText(_translate("TubesAlgeo", "<html><head/><body><p align=\"center\">7</p></body></html>"))
        self.label_19.setText(_translate("TubesAlgeo", "<html><head/><body><p align=\"center\">8</p></body></html>"))
        self.label_20.setText(_translate("TubesAlgeo", "<html><head/><body><p align=\"center\">9</p></body></html>"))
        self.label_21.setText(_translate("TubesAlgeo", "<html><head/><body><p align=\"center\">10</p></body></html>"))
        self.label_32.setText(_translate("TubesAlgeo", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Nama org</span></p></body></html>"))
        self.label_33.setText(_translate("TubesAlgeo", "<html><head/><body><p><span style=\" font-size:14pt;\">Best Result:</span></p></body></html>"))
        """
        self.menuOpen.setTitle(_translate("TubesAlgeo", "File"))
        self.actionFile.setText(_translate("TubesAlgeo", "File"))
        self.actionOpen.setText(_translate("TubesAlgeo", "Generate Database"))
        self.actionSave.setText(_translate("TubesAlgeo", "Load"))
        self.actionTest_File.setText(_translate("TubesAlgeo", "Test File"))"""
#from open import Open
#import resource
